apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: shprod
  name: wisland-feed-prod-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisland-feed-prod-canary
      version: v2
  template:
    metadata:
      labels:
        app: wisland-feed-prod-canary
        version: v2
    spec:
      imagePullSecrets:
        - name: registry-ali-hangzhou
        - name: registry-ali-sh-ee
      containers:
        - name: wisland-feed-prod-canary-server
          image: atom-sh-registry-vpc.cn-shanghai.cr.aliyuncs.com/mxrag/wisland-feed-prod:server-20250920142148
          imagePullPolicy: IfNotPresent
          env:
            - name: ENVIRONMENT
              value: prod
            - name: NACOS_ENDPOINT
              value: mse-886eff00-nacos-ans.mse.aliyuncs.com:8848
            - name: NACOS_NAMESPACE
              value: 3f36bb60-6861-4fad-a057-9bb6d9a4e51d
            - name: NACOS_ENABLE
              value: "true"
            - name: APP_PROFILE
              value: prod
            - name: aliyun_logs_wisland-feed-prod-canary-server
              value: stdout
            - name: SITE
              value: cn
          ports:
            - containerPort: 3500
              protocol: TCP
          resources:
            limits:
              cpu: 2
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 100Mi
          livenessProbe:
            tcpSocket:
              port: 3500
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 3500
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3

        - name: wisland-feed-prod-canary-worker
          image: atom-sh-registry-vpc.cn-shanghai.cr.aliyuncs.com/mxrag/wisland-feed-prod:worker-20250920142148
          imagePullPolicy: IfNotPresent
          env:
            - name: ENVIRONMENT
              value: prod
            - name: NACOS_ENDPOINT
              value: mse-886eff00-nacos-ans.mse.aliyuncs.com:8848
            - name: NACOS_NAMESPACE
              value: 3f36bb60-6861-4fad-a057-9bb6d9a4e51d
            - name: NACOS_ENABLE
              value: "true"
            - name: APP_PROFILE
              value: prod
            - name: aliyun_logs_wisland-feed-prod-canary-worker
              value: stdout
            - name: SITE
              value: cn
          resources:
            limits:
              cpu: 2
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 120
