name = "wisland-feed"
version = "0.1.0"
log = "debug,sqlx=off,h2=off,sea_orm=off"

[server]
host = "0.0.0.0"
port = 3500
api_prefix = "/api/v1/feed"

[database]
url = "postgresql://postgres:testpassword@127.0.0.1:5432/wisland_feed?sslmode=disable"
allow_migrate = true
allow_migration_fail = true
timeout_ms = 5000                                                                      # 5s
idle_timeout_ms = 600_000                                                              # 10 mins
acquire_timeout_ms = 3000                                                              # 3s
max_connections = 20
min_connections = 5

[llm]
# frequency_penalty =
temperature = 0.7
prompt_max_token = 6000
endpoint = "http://model-wismodel.prod.atominnolab.com/v1"
model = "WisModel-20250821-8B-strict"
api_key = "sk-GmE1ci8tMnVzuaOGsPSgLA"

[agent]
max_history = 10
plan_suffix = "<|plan|>"
search_plan_suffix = "<|search|>"
verifier_user_prompt = "## question:\n{question}\n\n## search result:\n{search_result}"

[search]
serp_api_key = "fa709c7ccbd9f970e4ad48da07f7ad4e6a6b0ac30e8f50682dba30f8a7d47e02"

[oss]
access_key_id = "access_key_id"
access_key_secret = "access_key_secret"
bucket = "bucket"
endpoint = "endpoint"
prefix = "prefix"

[rss]
max_prompt_number = 10
max_rss_paper = 1000
redis_prefix = "wisland-feed"
only_log_failed_jobs = true
arxiv_header_image = "https://info.arxiv.org/brand/images/brand-logo-primary.jpg"
temp_download_path = "/temp"

[rss.feed_redis]
url = ""
pool_size = 16
redis_key_default_expire = 600
redis_prefix = "wisland-feed"

# Named workers mapping for easier .env override by name
[rss.workers.verify_papers]
name = "verify_papers"
concurrency = 2
timeout_secs = 3600
retry = 1

[rss.workers.verify_one_paper_prompt_pair]
name = "verify_one_paper_prompt_pair"
concurrency = 2
timeout_secs = 600
retry = 1

[rss.workers.pull_sources]
name = "pull_sources"
concurrency = 1
timeout_secs = 36000
retry = 1
cron = "1 * * * * *"

[rss.workers.parse_rss_xml]
name = "parse_rss_xml"
concurrency = 1
timeout_secs = 36000
retry = 1
cron = "*/30 * * * * *"

[rss.workers.update_user_interest_metadata]
name = "update_user_interest_metadata"
concurrency = 1
timeout_secs = 36000
retry = 1
cron = "@daily"

[rss.workers.update_user_interest_metadata_once]
name = "update_user_interest_metadata_once"
concurrency = 2
timeout_secs = 600
retry = 1


[rss.workers.download_rss_source_files]
name = "download_rss_source_files"
concurrency = 1
timeout_secs = 36000
retry = 1
cron = "@daily"
