name = "wisland-feed-dev"
log = "debug,sqlx=off,h2=off,sea_orm=off,hyper_util=off"

[database]
url = "postgresql://postgres:lckL0SRWsehuBHm11iRPF607LHtQKDEm@pgm-t4nt0q661897ui8j.pgsql.singapore.rds.aliyuncs.com:5432/wisland_feed?sslmode=disable"

[llm]
endpoint = "http://dev-wismodel.dev.atominnolab.com/v1"
model = "WisModel-20250906"
api_key = "sk-GmE1ci8tMnVzuaOGsPSgLA"

[agent_redis]
url = "redis://:qqtGrRntjDpMjcf5+88PgQ@r-t4n1mhl69h4x1f8td8.redis.singapore.rds.aliyuncs.com:6379/0"
pool_size = 16
