FROM rust:1.88.0

WORKDIR /app


RUN apt-get update && apt-get install -y --no-install-recommends poppler-utils && rm -rf /var/lib/apt/lists/*

ARG APP_PROFILE

ENV APP_PROFILE=${APP_PROFILE}

# copy binary from build stage
COPY target/release/worker .

# copy base configuration files
COPY base.toml .

# copy profile-specific configuration file
COPY base.${APP_PROFILE}.toml .

RUN chmod +x worker

CMD ["./worker"]
