apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prod-ns
  name: nginx-model-prod-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-model-prod-canary
      version: v2
  template:
    metadata:
      labels:
        app: nginx-model-prod-canary
        version: v2
    spec:
      containers:
        - name: nginx-model-prod-canary
          image: crpi-hytqalx0cm8oqxr4.cn-hangzhou.personal.cr.aliyuncs.com/mxrag/nginx-model-prod:20250920142148
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: '0.25m'
              memory: 0.5Gi
            requests:
              cpu: '0.25m'
              memory: 0.5Gi
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
      dnsPolicy: ClusterFirst
      nodeSelector:
        type: virtual-kubelet
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 120
      tolerations:
        - effect: NoSchedule
          key: virtual-kubelet.io/provider
          operator: Exists