apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/canary: 'true'
    alb.ingress.kubernetes.io/canary-by-header: X-Canary
    alb.ingress.kubernetes.io/canary-by-header-value: grey
    alb.ingress.kubernetes.io/order: '1'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80},{"HTTPS": 443}]'
  labels:
    ingress-controller: alb
  name: wisland-feed-prod-ingress-canary
  namespace: prod-ns
spec:
  ingressClassName: alb
  rules:
    - host: wisland-feed.wispaper.inner
      http:
        paths:
          - backend:
              service:
                name: wisland-feed-prod-service-canary
                port:
                  number: 3500
            path: /
            pathType: Prefix
    - host: wisland-feed-canary.atominnolab.com
      http:
        paths:
          - backend:
              service:
                name: wisland-feed-prod-service-canary
                port:
                  number: 3500
            path: /
            pathType: Prefix      
  tls:
    - hosts:
        - wisland-feed-canary.atominnolab.com
      secretName: tls-atominnolab.com
