name: deploy_ali_ack-dev

on:
  push:
    branches: [dev]
  pull_request_target:
    branches: [dev]
    types: [closed]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  KUBECTL_VERSION: v1.32.2
  NAMESPACE: dev-ns
  REPO_NS: mxrag-dev
  REGION_ID: ap-southeast-1
  DEPLOYMENT: wisland-feed-dev

  REPO: ${{ secrets.ALI_DOCKER_REGISTRY }}
  REPO_USER: ${{ secrets.ALI_DOCKER_REGISTRY_USERNAME_PENGHAO }}
  REPO_PASSWD: ${{ secrets.ALI_DOCKER_REGISTRY_PASSWD_PENGHAO }}
  FEISHU_WEBHOOK_URL_DEV: ${{ secrets.FEISHU_WEBHOOK_URL_DEV }}
  KUBECONFIG_DEV: ${{ secrets.KUBECONFIG_DEV }}

jobs:
  deploy_to_dev:
    # 仅在以下情况运行：
    # 1. push 到 dev（github.event_name == 'push'）
    # 2. PR 合并到 dev（github.event_name == 'pull_request_target' 且 merged == true）
    # 3. 手动触发（github.event_name == 'workflow_dispatch'）
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'pull_request_target' && github.event.pull_request.merged == true) ||
      github.event_name == 'workflow_dispatch'
    name: build_and_push
    permissions:
      contents: write
    runs-on: [ubuntu-22.04]
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust-stable
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.88.0
          override: true
      
      - name: Set proxy
        run: |
          rm -rf ~/.gitconfig || true
          git config --global url."https://${{ secrets.GH_ACCESS_TOKEN }}@github.com".insteadOf ssh://git@github.com
          git config --global credential.helper store

      - name: Building
        shell: bash
        run: cargo build -r

      - name: Generate Docker Tag
        id: docker_tag
        run: |
          datetime_now=$(TZ='Asia/Shanghai' date "+%Y%m%d%H%M%S")
          echo "DOCKER_TAG=${datetime_now}" >> $GITHUB_ENV

      - name: Log in to Aliyun ACR
        run: |
          docker login \
            -u ${{ env.REPO_USER }} \
            -p ${{ env.REPO_PASSWD }} \
            ${{ env.REPO }}

      - name: Build and Push Docker Image
        run: |
          sudo apt-get update && sudo apt-get install -y retry
          docker build --build-arg APP_PROFILE=dev -f Dockerfile.server -t ${{ env.REPO }}/${{ env.REPO_NS }}/${{ env.DEPLOYMENT }}:server-${{ env.DOCKER_TAG }} .
          docker build --build-arg APP_PROFILE=dev -f Dockerfile.worker -t ${{ env.REPO }}/${{ env.REPO_NS }}/${{ env.DEPLOYMENT }}:worker-${{ env.DOCKER_TAG }} .
          retry -t 5 -- docker push ${{ env.REPO }}/${{ env.REPO_NS }}/${{ env.DEPLOYMENT }}:server-${{ env.DOCKER_TAG }}
          retry -t 5 -- docker push ${{ env.REPO }}/${{ env.REPO_NS }}/${{ env.DEPLOYMENT }}:worker-${{ env.DOCKER_TAG }}

      - name: Setup kubectl
        uses: ./.github/actions/setup-kubectl-ack
        with:
          kubectl-version: ${{ env.KUBECTL_VERSION }}
          kubeconfig-env: ${{ env.KUBECONFIG_DEV }}

      - name: Update
        run: |
          kubectl -n "${{ env.NAMESPACE }}" set image deployment/${{ env.DEPLOYMENT }} \
            ${{ env.DEPLOYMENT }}-server=${{ env.REPO }}/${{ env.REPO_NS }}/${{ env.DEPLOYMENT }}:server-${{ env.DOCKER_TAG }} \
            ${{ env.DEPLOYMENT }}-worker=${{ env.REPO }}/${{ env.REPO_NS }}/${{ env.DEPLOYMENT }}:server-${{ env.DOCKER_TAG }}

      - name: Notify Feishu - update
        uses: ./.github/actions/send-feishu
        with:
          webhook: ${{ env.FEISHU_WEBHOOK_URL_DEV }}
          status-emoji: "🟢"
          title: "ACK: ${{ env.DEPLOYMENT }} released"
          details: "仓库: ${{ github.repository }}%0A分支: ${{ github.ref_name }}%0A提交: ${{ github.sha }}%0A镜像: ${{ env.DOCKER_TAG }}"

  notify_failed_job:
    name: notify_failed_job
    needs: [deploy_to_dev]
    if: always() && needs.deploy_to_dev.result == 'failure'
    runs-on: [ubuntu-22.04]
    steps:
      - uses: actions/checkout@v4
      
      - name: Notify Feishu - failed
        uses: ./.github/actions/send-feishu
        with:
          webhook: ${{ env.FEISHU_WEBHOOK_URL_DEV }}
          status-emoji: "🔴"
          title: "ACK: ${{ env.DEPLOYMENT }} failed"
          details: "仓库: ${{ github.repository }}%0A分支: ${{ github.ref_name }}%0A提交: ${{ github.sha }}"